var dataModel = new Model({
	SPREADSHEET_URL : "https://spreadsheets.google.com/feeds/list/0ArMvT6nVqkMPdHBkazE2ZGZvVXQyYzFmQ2dSckRiWVE/od6/public/basic?alt=json-in-script&callback=[c]",
	worksheet:null,
	dataItems:null,
	headings:{
		ticker:"Ticker",
		industry:"Industry",
		market:"Market Cap",
		price:"Price",
		change:"Change",
		volume:"Volume"
	},
	viewHolderCN : "viewHolder",
	viewHeaderCN : "header",
	viewContainerCN : "container",
	dataTableCN : "datatable",
	viewInnerContainerCN : "inner",
	searchHolderCN : "searchHolder",
	navHolderCN : "nav",
	searchFaqCN : "faq",
	searchHelpCN : "help",
	navRightCN : "right",
	navhomeCN : "home",
	dataGridHeaderCopy : "DataGrid Control Panel",
	dataGridTitleCopy : "DATA<span class='secondColour'>GRID</span>",
	faqCopy : "<p>FAQ</p>",
	helpCopy : "<p>HELP</p>",
	previewCopy : "<p>Preview</p>",
	activityCopy : "<p>Activity</p>",
	controlCopy : "<p>Control</p>",
	issueCopy : "<p>Issue</p>",
	overviewCopy : "<p>Overview</p>",
	adminCopy : "<p>Admin</p>",
	profileCopy : "<p>My Profile</p>",
	currentNav : "",
});
